version: 0.2

phases:
  pre_build:
    commands:
      - echo instalando pacotes do npm
      - npm install
  build:
    commands:
      - echo Criando Build do projeto
      - npm run build
  post_build:
    commands:
      - echo Removendo arquivos desnecessários
      # - rm -rf node_modules/

artifacts:
  base_directory: '.'
  files:
    - '**/*'
